### ISSUE TITLE
Libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by ghost** [RapidsOfficial/Rapids#1]
@mrdecafee

In debug.log (saw in windows, ubuntu and raspbian) there is this error-message, that should be fixed.
This is an errror in one (or some) pictures. How to fix it, you can see it here:
https://gist.github.com/bluenex/0af2f41fda9954df73a8

Thank you :-)

**Comment by mrjberlin** [comment]
We will review the issue, suggested solution and update the code in a timely manner if required.

Thank you for your submission!
