### ISSUE TITLE
Doesn't work for systems with libboost_system.so.1.65.1

### ISSUE THREAD

**Issue by Marianne-Abdelmalek** [RapidsOfficial/Rapids#11]
the rapids-cli depends on older version of libboost_system.so.1.58.0

When I tried to link my 65 version to 58 it gave another error:
undefined symbol: _ZN5boost11this_thread5hiden9sleep_forERK8timespec

**Comment by Marianne-Abdelmalek** [comment]
Hahaha you just close the issue? Why bother???

**Comment by crycy1** [comment]
The issue is now resolved...
